version: '3'
services: # each service becomes a container that has a host name
  redis:
    image: "redis:alpine"
    command: redis-server
    expose:
      - 6379
    volumes: # specify the path 
      - db-data:/data
  # web:
  #   depends_on:
  #     - redis
  #   build: .
    ports:
      - "5001:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
volumes:
  db-data:
